package com.thoughtworks.training.guessnumber;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.common.base.Strings;
import com.google.common.io.LineReader;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.io.InputStreamReader;


public class App {

    public static void main(String[] args) throws IOException {
        LineReader lineReader=new LineReader(new InputStreamReader(System.in));
        String line;

        XmlBeanFactory beanFactory=new XmlBeanFactory(
                new ClassPathResource("./context.xml"));
        GuessNumberGame lister=beanFactory.getBean(GuessNumberGame.class);

        while (!Strings.isNullOrEmpty((line=lineReader.readLine()))){
            System.out.println(lister.process(line));
        }

    }


}
