package com.thoughtworks.training.guessnumber;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AppTest {
    @Test
    public void shouldGuessNubmber() {
        String output = new GuessNumberGame(new OddRule()).process("1 2 3 4 5");
        assertThat(output,is("1 3 5"));
    }

    @Test
    public void shouldGuessNubmber2() {
        String output = new GuessNumberGame(new EvenRule()).process("3 4 5 6 7");
        assertThat(output,is("4 6"));
    }

    @Test
    public void shouldGuessNubmber3() {
        String output = new GuessNumberGame(new OddRule(),new AddRule()).process("6 7 8 9");
        assertThat(output,is("9 11"));
    }

}
